# Generated by Django 4.0.6 on 2022-07-04 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contatp',
            new_name='Contato',
        ),
    ]
